### ISSUE TITLE
Issue: TRX file for VS: 2015: App crash (Fixed)

### ISSUE THREAD

**Issue by Praveenpvs** [NivNavick/trxer#14]
Hi,
Thanks for this nice tool. Just now tested this with VS 2015 TRX file (generated from VSTest.Console.Exe).

Wanted to share a fix, so that it will help others in using this one.

Application is crashing at line where it is removing the namespace from the assembly name. So, just placed a condition in Trxer.xslt (line#13, RemoveAssemblyName method).

public string RemoveAssemblyName(string asm) 
    {
      if (asm.IndexOf(',') > 0)
        return asm.Substring(0,asm.IndexOf(','));
       else
        return asm;
    }

Now, it started generating the file without any problems.

Some other issues might turn up, e.g. Duration not present etc, so just get the project and fix. I believe the fixes might be limited to the XSLT file.

**Comment by magestican** [comment]
Thank you man :D

**Comment by gnaneswarreddy** [comment]
Can you upload the exe as i was unable to compile it?

**Comment by Praveenpvs** [comment]
Hi,
Could not see your request on time, attached is the exe file:
[TrxerConsole.zip](https://github.com/NivNavick/trxer/files/169680/TrxerConsole.zip)

**Comment by Praveenpvs** [comment]
Hi,
Could not see your request on time, attached is the full package with EXE file. You need not re-compile, just refer to this directory and run the console command as suggested by the author.
[TrxerConsole.zip](https://github.com/NivNavick/trxer/files/169687/TrxerConsole.zip)

**Comment by gnaneswarreddy** [comment]
I am still seeing APP Crash even after doing the change. Could you please let me know any other changes needs to be done

**Comment by Praveenpvs** [comment]
Did you use the package I have shared?

If you are still getting, better you open the project in VS and debug. I believe the error would be in the XSLT file. Some TRX files are a bit different w.r.to the VS version which causes this issue. 

In the code, you can remove transformations which you do not need (e.g. Top 5 slowest tests).
